#!/usr/bin/env python3
"""
Generate updi/updi_device_table.h from the pymcuprog device packs in
reference/pymcuprog/deviceinfo/devices/.

Each device pack is a Python module defining DEVICE_INFO (a dict). We exec it with a
stub for the `pymcuprog.deviceinfo.eraseflags` import, then emit one C initializer row
per part. Run from the repo root:  python scripts/gen_device_table.py

This keeps the on-device geometry table byte-for-byte faithful to Microchip's DFP data
(no hand transcription), which matters because a wrong page size or NVMCTRL base just
silently corrupts a flash write.
"""
import os
import sys
import types

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEV_DIR = os.path.join(ROOT, "reference", "pymcuprog", "deviceinfo", "devices")
OUT = os.path.join(ROOT, "updi", "updi_device_table.h")

# Curated v1 part list (must have a matching <name>.py device pack present).
PARTS = [
    # AVR EA series (NVM P:3, 24-bit). Only avr64ea* are published in pymcuprog today.
    "avr64ea28", "avr64ea32", "avr64ea48",
    # tinyAVR 0/1/2 (NVM P:0, 16-bit)
    "attiny412", "attiny416", "attiny814", "attiny816",
    "attiny1614", "attiny1616", "attiny3216", "attiny3226",
    "attiny827", "attiny1627",
    # megaAVR 0 (NVM P:0, 16-bit)
    "atmega808", "atmega809", "atmega1608", "atmega1609",
    "atmega3208", "atmega3209", "atmega4808", "atmega4809",
]


def load_device_info(name):
    """Exec a device pack module and return its DEVICE_INFO dict."""
    path = os.path.join(DEV_DIR, name + ".py")
    if not os.path.exists(path):
        return None
    # Stub the eraseflags import the packs use.
    eraseflags = types.ModuleType("pymcuprog.deviceinfo.eraseflags")

    class ChiperaseEffect:  # noqa: N801 - mirror the real name
        ALWAYS_ERASED = "ALWAYS_ERASED"
        CONDITIONALLY_ERASED_AVR = "CONDITIONALLY_ERASED_AVR"
        NOT_ERASED = "NOT_ERASED"

    eraseflags.ChiperaseEffect = ChiperaseEffect
    pkg = types.ModuleType("pymcuprog")
    sub = types.ModuleType("pymcuprog.deviceinfo")
    sys.modules.setdefault("pymcuprog", pkg)
    sys.modules.setdefault("pymcuprog.deviceinfo", sub)
    sys.modules["pymcuprog.deviceinfo.eraseflags"] = eraseflags
    ns = {}
    with open(path, "r") as f:
        exec(f.read(), ns)  # noqa: S102 - trusted local file
    return ns["DEVICE_INFO"]


def row(info):
    name = info["name"]
    addr_size = info.get("address_size", "16-bit")
    is24 = addr_size == "24-bit"
    address_bytes = 3 if is24 else 2
    # Within the v1 set, 24-bit == AVR EA == NVM P:3; 16-bit == P:0.
    variant = "UpdiNvmVariantP3" if is24 else "UpdiNvmVariantP0"
    fields = [
        ("0x%06X" % info["device_id"]),
        ('"%s"' % name),
        ("0x%08XUL" % info["flash_address_byte"]),
        ("0x%XUL" % info["flash_size_bytes"]),
        ("0x%X" % info["flash_page_size_bytes"]),
        ("0x%08XUL" % info["eeprom_address_byte"]),
        ("0x%X" % info["eeprom_size_bytes"]),
        ("0x%X" % info["eeprom_page_size_bytes"]),
        ("0x%08XUL" % info["fuses_address_byte"]),
        ("0x%X" % info["fuses_size_bytes"]),
        ("0x%08XUL" % info["user_row_address_byte"]),
        ("0x%X" % info["user_row_size_bytes"]),
        ("0x%X" % info["user_row_page_size_bytes"]),
        ("0x%08XUL" % info["signatures_address_byte"]),
        ("0x%08XUL" % info["nvmctrl_base"]),
        ("0x%08XUL" % info["syscfg_base"]),
        ("%d" % address_bytes),
        variant,
    ]
    return "    {" + ", ".join(fields) + "},"


def main():
    rows = []
    skipped = []
    for p in PARTS:
        info = load_device_info(p)
        if info is None:
            skipped.append(p)
            continue
        rows.append(row(info))
    header = [
        "/**",
        " * @file updi_device_table.h",
        " * @brief Generated device geometry table. DO NOT EDIT BY HAND.",
        " *",
        " * Generated by scripts/gen_device_table.py from the pymcuprog device packs",
        " * (Microchip DFP data). Fields, in order:",
        " *   device_id, name, flash_address, flash_size, flash_page_size,",
        " *   eeprom_address, eeprom_size, eeprom_page_size, fuses_address, fuses_size,",
        " *   userrow_address, userrow_size, userrow_page_size, sigrow_address,",
        " *   nvmctrl_base, syscfg_base, address_bytes, nvm_variant",
        " */",
        "#pragma once",
        "",
        "/* clang-format off */",
        "static const UpdiDevice updi_device_table[] = {",
        *rows,
        "};",
        "/* clang-format on */",
        "",
    ]
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(header))
    print("Wrote %s with %d devices." % (OUT, len(rows)))
    if skipped:
        print("Skipped (no device pack): %s" % ", ".join(skipped))


if __name__ == "__main__":
    main()
